type: 'python:3.7.9'
name: app

dependencies:
    python3:
        pipenv: "2022.12.19"


hooks:
    build: |
        set -eu 
        pip install -r requirements.txt

    web:
        # Start your app with the configuration you define
        # You can replace the file location with your location
        commands:
            start: uvicorn main:app

