type: 'python:3.8'
name: app

dependencies:
    python3:
        pipenv: "2022.12.19"


hooks:
    build: |
        set -eu 
        pip install -r requirements.txt
web:
    locations:
        "/":
            # The command to start your application using uvicorn
            command: "uvicorn main:app"